### ISSUE TITLE
Add DigitalOcean provider

### ISSUE THREAD

**Issue by fabdouglas** [ligoj/plugin-prov#105]
For Digital Ocean, there s no pricing API, but only a web page:
https://www.digitalocean.com/pricing/
Service to import in catalog:
- compute
- database (managed)
- storage (all of them: block,..)
- support : managed in the code, like Azure

For non regression, use the native calculator: https://www.digitalocean.com/pricing/calculator/

Another way to get the prices is using this URL: https://www.digitalocean.com/assets/js/pricing-calculator-118c100f.js
You can get this URL naming when inpecting the home page of the calculator:
Locate this part in https://www.digitalocean.com/pricing/calculator/: 
``` html
<script src="/assets/js/pricing-calculator-118c100f.js"></script>
```

Thenn, inside this raw Javascript, extract the Javascript to transform into JSON:
``` javascript
{dropletType:"Standard",...}
```

**Comment by ligoj** [comment]
Provider is now available there : https://github.com/ligoj/plugin-prov-digitalocean
