### ISSUE TITLE
Add outscale provider

### ISSUE THREAD

**Issue by fabdouglas** [ligoj/plugin-prov#111]
Pricing: https://en.outscale.com/pricing/
https://en.outscale.com/pricing/how-pricing-works/

**Comment by fabdouglas** [comment]
Reservation instance discount formula: https://wiki.outscale.net/display/EN/Getting+the+Price+of+Your+Instances#GettingthePriceofYourInstances-CalculatingthePriceofReservedInstances

**Comment by ligoj** [comment]
Proiver is released in https://github.com/ligoj/plugin-prov-outscale
