### ISSUE TITLE
CPU burst icon is missing

### ISSUE THREAD

**Issue by ligoj** [ligoj/plugin-prov#124]
CPU burst icon is missing in the dropdown of the instance modal.

![image](https://user-images.githubusercontent.com/26227618/91169696-0e921300-e6d8-11ea-9f9a-6a2f3480a6f2.png)

Use this icon:
![image](https://user-images.githubusercontent.com/26227618/91169793-371a0d00-e6d8-11ea-8adc-878554ef72b5.png)

**Comment by fabdouglas** [comment]
A more and suitable icon should be used : `wave-square`
![image](https://user-images.githubusercontent.com/579170/107873104-0b6e2780-6eb0-11eb-8cc6-356be7661fbc.png)
