### ISSUE TITLE
Avoid overflow for multiline select in storage selection 

### ISSUE THREAD

**Issue by ligoj** [ligoj/plugin-prov#127]
While selecting the storage in the instance/database storage, multilines may appear. This is acceptable, however, the trailing price should not hide partially the next item.

![image](https://user-images.githubusercontent.com/26227618/91215361-af9ebf00-e714-11ea-9b58-e21a20dead13.png)

The related issue is getting an incomplete selection in some scenario:
![image](https://user-images.githubusercontent.com/26227618/91215708-2b007080-e715-11ea-91db-9dd5f91966f6.png)

**Comment by fdaugan** [comment]
For this issue, use the `dropdownAutoWidth`Select2 option: 
```
$some.select2({
  ...
  dropdownAutoWidth: true,
});
```
No extra CSS required.
Documentation: https://select2.github.io/select2/ > dropdownAutoWidth
`When set to true attempts to automatically size the width of the dropdown based on content inside`
