### ISSUE TITLE
Add title while edition quote

### ISSUE THREAD

**Issue by fdaugan** [ligoj/plugin-prov#146]
In the modal displayed while editing a quote, there is no title.
As title, add the provider icon and the current project name.

![image](https://user-images.githubusercontent.com/579170/116809949-337d3680-ab41-11eb-9d0c-258dd0d481c1.png)

**Comment by acleret69** [comment]
<img width="601" alt="Capture d’écran 2021-07-05 à 13 34 02" src="https://user-images.githubusercontent.com/72598333/124465430-b2872900-dd95-11eb-937d-920daf665e10.png">
