### ISSUE TITLE
Country flags are no more displayed

### ISSUE THREAD

**Issue by fdaugan** [ligoj/plugin-prov#164]
Flag of countries related to region/location are not displayed in suggest UI components
![image](https://user-images.githubusercontent.com/579170/124444901-59ac9600-dd7f-11eb-844d-f2926ed885c0.png)

**Comment by acleret69** [comment]
<img width="598" alt="Capture d’écran 2021-08-05 à 09 30 07" src="https://user-images.githubusercontent.com/72598333/128309779-ace2c2c6-6746-4a0d-b4a3-dc5269ee5e3e.png">

**Comment by fdaugan** [comment]
The flags are still not visible

**Comment by fdaugan** [comment]
This issue is related to a AWS catalog import where zone details where not imported.
