### ISSUE TITLE
Software list is cannot be filtered

### ISSUE THREAD

**Issue by fdaugan** [ligoj/plugin-prov#167]
While typing in the suggest (Select2 component) to filter the software, the items are not filtered accordingly to the text.

![image](https://user-images.githubusercontent.com/579170/127774524-e3283778-9a80-4374-9b28-6dfcdad3f123.png)

**Comment by acleret69** [comment]
<img width="602" alt="Capture d’écran 2021-12-10 à 11 06 36" src="https://user-images.githubusercontent.com/72598333/145556292-4259f897-023a-428e-9721-f1bb48c687c4.png">
