### ISSUE TITLE
Typo in FR label of preferred location

### ISSUE THREAD

**Issue by fdaugan** [ligoj/plugin-prov#216]
There: https://ligoj-rec.web-enedis.fr/#/prov/catalog
With FR locale.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/579170/176796521-5d41ad80-373a-44bc-b799-6fd8818087f9.png">

"préféré" -> "préférée"

**Comment by acleret69** [comment]
<img width="600" alt="Capture d’écran 2022-07-12 à 10 30 35" src="https://user-images.githubusercontent.com/72598333/178446444-9168a245-4ac5-4dad-8973-7da3d67c557b.png">
