### ISSUE TITLE
Panel toggle button may not reachable on small devices

### ISSUE THREAD

**Issue by fdaugan** [ligoj/plugin-prov#23]
On small device (landscape mode), the panel toggle button may not be visible.
This button should be moved to the top for a more common usage.

![image](https://user-images.githubusercontent.com/579170/52229815-1865e280-28b6-11e9-8a55-b5a09996aeab.png)

**Comment by acleret69** [comment]
<img width="881" alt="Capture d’écran 2021-07-06 à 10 45 36" src="https://user-images.githubusercontent.com/72598333/124570558-4cf37500-de47-11eb-9413-bef1535053f1.png">
<img width="876" alt="Capture d’écran 2021-07-06 à 10 45 44" src="https://user-images.githubusercontent.com/72598333/124570582-5250bf80-de47-11eb-896e-184a3358d328.png">
