### ISSUE TITLE
Replace barchart's legend text by an inner icon

### ISSUE THREAD

**Issue by fdaugan** [ligoj/plugin-prov#39]
Replace barchart's legend text by an inner icon. The icon to use corresponds to the one used in the assumption panel.

![image](https://user-images.githubusercontent.com/579170/52784825-a7ad8b80-3056-11e9-9408-0142dba7d02f.png)

![image](https://user-images.githubusercontent.com/579170/52784877-c7dd4a80-3056-11e9-8a75-ca927d304bd5.png)

**Comment by fdaugan** [comment]
In other words, in the legend of the barchart, instead of having the text "instance", show the instance icon.

**Comment by acleret69** [comment]
<img width="108" alt="Capture d’écran 2021-07-06 à 09 23 04" src="https://user-images.githubusercontent.com/72598333/124559223-c6856600-de3b-11eb-93c7-e6b87029e14d.png">

**Comment by fdaugan** [comment]
I do not experience the same result. I think the CSS file is missing
![image](https://user-images.githubusercontent.com/579170/128377084-47f93704-4bfa-4573-8757-0e6c06d9f2c0.png)
