### ISSUE TITLE
Replace pencil icon by the click on the resource name

### ISSUE THREAD

**Issue by fdaugan** [ligoj/plugin-prov#54]
In each resources table, in addition of the pencil icon, click on the resource name should also disply the modal for modification

**Comment by acleret69** [comment]
<img width="187" alt="Capture d’écran 2021-07-06 à 15 58 06" src="https://user-images.githubusercontent.com/72598333/124612860-f7cd5880-de72-11eb-8583-dcbe79c35bf9.png">
